FROM python:3
MAINTAINER AnnatarHe <iamhele1994@gmail.com>

# ENV http_proxy http://your.agent.proxy:port
# ENV https_proxy http://your.agent.proxy:port

RUN pip install scrapy redis psycopg2
WORKDIR /py

CMD ["/bin/bash"]
